import { type NextPage } from "next";
import Head from "next/head";

import urlRoutePairs from "../db/url";
import { useEffect, useState } from "react";

import { GrHome } from "react-icons/gr";
import { AiFillGithub } from "react-icons/ai";

interface Item {
  source: string;
  destination: string;
}

export const getStaticProps = () => {
  return {
    props: {
      owner_first_name: process.env.OWNER_FIRST_NAME,
      owner_last_name: process.env.OWNER_LAST_NAME,
      owner_github: process.env.GITHUB_URL,
      owner_homepage: process.env.OWNER_HOMEPAGE,
    },
  };
};

const Home: NextPage = (props: any) => {
  const [host, setHost] = useState<string>("");

  useEffect(() => {
    setHost(window.location.href);
  }, []);

  return (
    <>
      <Head>
        <title>{props.owner_first_name + `'s URL shortener`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="p-4">
        <h1>Welcome to {props.owner_first_name + `'s `}URL Shortener</h1>
        <h2 className="pb-2">
          Application is running at{" "}
          <span className="font-mono text-info">{host}</span>
        </h2>
        <div className="flex space-x-2">
          <a className="btn-sm btn text-primary" href={props.owner_homepage}>
            <GrHome></GrHome>
          </a>

          <a className="btn-sm btn" href={props.owner_github}>
            <AiFillGithub></AiFillGithub>
          </a>
        </div>

        <div className="flex flex-col overflow-x-auto">
          <h2 className="pb-4 text-center text-2xl text-primary">URLs</h2>
          <hr></hr>
          <table className="table w-full">
            <thead>
              <tr>
                <td>#</td>
                <th>Source</th>
                <th>Destination</th>
              </tr>
            </thead>
            <tbody>
              {urlRoutePairs?.length > 0 ? (
                urlRoutePairs.map((item: Item, idx: number) => (
                  <tr key={idx}>
                    <td>{idx}</td>
                    <td>
                      <a href={item.source}>
                        {host}
                        {item.source}
                      </a>
                    </td>
                    <td>
                      <a href={item.destination}>{item.destination}</a>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={3} className="bg-info text-center text-black">
                    There are no URLs to display.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Home;
