import { type NextPage } from "next";
import Head from "next/head";

import urlRoutePairs from "../db/url";
import { useEffect, useState } from "react";

import { GrHome } from "react-icons/gr";
import { AiFillGithub } from "react-icons/ai";
import { IconContext } from "react-icons";

interface Item {
  source: string;
  destination: string;
}

export const getStaticProps = () => {
  return {
    props: {
      owner_first_name: process.env.OWNER_FIRST_NAME,
      owner_last_name: process.env.OWNER_LAST_NAME,
      owner_github: process.env.GITHUB_URL,
      owner_homepage: process.env.OWNER_HOMEPAGE,
    },
  };
};

const Home: NextPage = (props: any) => {
  const [host, setHost] = useState<string>("");

  useEffect(() => {
    setHost(window.location.href);
  });

  return (
    <>
      <Head>
        <title>{props.owner_first_name + `'s URL shortener`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="p-4">
        <h1>Welcome to {props.owner_first_name + `'s `}URL Shortener</h1>
        <h2 className="pb-2">
          Application is running at{" "}
          <span className="font-mono text-info">{host}</span>
        </h2>
        <div className="flex space-x-2">
          <a className="btn-sm btn text-primary" href={props.owner_homepage}>
            <GrHome></GrHome>
          </a>

          <a className="btn-sm btn" href={props.owner_github}>
            <AiFillGithub></AiFillGithub>
          </a>
        </div>

        <div className="flex flex-col overflow-x-auto">
          <h2 className="pb-4 text-center text-2xl text-primary">URLs</h2>
          <hr></hr>
          <table className="table w-full">
            <thead>
              <tr>
                <td>#</td>
                <th>Source</th>
                <th>Destination</th>
              </tr>
            </thead>
            <tbody>
              {urlRoutePairs?.length > 0 ? (
                urlRoutePairs.map((item: Item, idx: number) => (
                  <tr>
                    <td> {idx} </td>
                    <td>
                      <a href={item.source}>
                        {host}
                        {item.source}
                      </a>
                    </td>
                    <td>
                      <a href={item.destination}>{item.destination}</a>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={3} className="bg-info text-center text-black">
                    There are no URLs to display.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

const favicon = (
  <svg
    stroke="currentColor"
    fill="currentColor"
    strokeWidth={0}
    viewBox="0 0 1024 1024"
    height="1em"
    width="1em"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path d="M574 665.4a8.03 8.03 0 0 0-11.3 0L446.5 781.6c-53.8 53.8-144.6 59.5-204 0-59.5-59.5-53.8-150.2 0-204l116.2-116.2c3.1-3.1 3.1-8.2 0-11.3l-39.8-39.8a8.03 8.03 0 0 0-11.3 0L191.4 526.5c-84.6 84.6-84.6 221.5 0 306s221.5 84.6 306 0l116.2-116.2c3.1-3.1 3.1-8.2 0-11.3L574 665.4zm258.6-474c-84.6-84.6-221.5-84.6-306 0L410.3 307.6a8.03 8.03 0 0 0 0 11.3l39.7 39.7c3.1 3.1 8.2 3.1 11.3 0l116.2-116.2c53.8-53.8 144.6-59.5 204 0 59.5 59.5 53.8 150.2 0 204L665.3 562.6a8.03 8.03 0 0 0 0 11.3l39.8 39.8c3.1 3.1 8.2 3.1 11.3 0l116.2-116.2c84.5-84.6 84.5-221.5 0-306.1zM610.1 372.3a8.03 8.03 0 0 0-11.3 0L372.3 598.7a8.03 8.03 0 0 0 0 11.3l39.6 39.6c3.1 3.1 8.2 3.1 11.3 0l226.4-226.4c3.1-3.1 3.1-8.2 0-11.3l-39.5-39.6z"></path>
  </svg>
);

export default Home;
